version: '3.8'


volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }
  static_volume:
  media_volume:



services:
  monolith_backend:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: monolith_backend
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    depends_on:
      - monolith_postgres
    networks:
      - monolith
      - user

      
  monolith_postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: monolith_postgres
    container_name: monolith_postgres
    ports:
      - 54322:5432
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - monolith

networks:
    monolith:
    user:
      external:
        name: user