version: '3.8'


volumes:
  production_postgres_data: { }
  production_postgres_data_backups: { }
  static_volume:
  media_volume:


services:
  user_backend:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    container_name: users-ms
    image: users_backend
    command: /start
    volumes:
      - .:/app
    ports:
      - 8001:8000
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    depends_on:
      - user_db
    networks:
      - user

      
  user_db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: user_postgres
    container_name: user_db
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:cached
      - production_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - user

  user_nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: user_nginx_image
    container_name: user_nginx_container
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media/
    ports:
      - 81:81
      - 444:444
    depends_on:
      - user_backend
    command: /bin/bash -c "chown -R nginx:nginx /var/www/static && chmod -R 755 /var/www/static && nginx -g 'daemon off;'"
    networks:
      - user

networks:
  user: 
    name: user